apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    signingConfigs {
        release {
            keyAlias 'and2long'
            keyPassword 'and2long'
            storeFile file('../and2long.jks')
            storePassword 'and2long'
        }
    }
    compileSdkVersion 37
    defaultConfig {
        applicationId "com.and2long.applist"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 12
        versionName "2.0.1"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig = signingConfigs.release
        }
        debug {
            signingConfig = signingConfigs.release
        }
    }
    namespace = 'com.and2long.applist'
    buildFeatures {
        compose = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
}

dependencies {
    implementation platform('androidx.compose:compose-bom:2026.05.01')
    implementation 'androidx.activity:activity-compose:1.13.0'
    implementation 'androidx.compose.foundation:foundation'
    implementation 'androidx.compose.material:material-icons-core'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.core:core-ktx:1.18.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.11.0'

    debugImplementation 'androidx.compose.ui:ui-tooling'
}
